[package]
name = "yamux"
version = "0.1.0"
authors = ["Linfeng Qian <thewawar@gmail.com>"]

[dependencies]
crossbeam-channel = "0.3"
bytes = "0.4"
byteorder = "1.2"
fnv = "1.0"
futures = "0.1"
tokio-codec = "0.1"
tokio-io = "0.1"